/*
 * Tacheles - Grammatik-Module (Baender A0 bis C2)
 * Klassisches Script (kein ES-Modul, kein fetch, keine Abhaengigkeiten), damit es
 * per file:// direkt im Browser laeuft. Definiert genau EIN Global:
 *   window.TACHELES_GRAMMAR = { version, modules }
 *
 * Die App merged TACHELES_GRAMMAR.modules beim Init in CONTENT.modules (defensiv:
 * fehlendes Global wird toleriert, doppelte Modul-IDs werden zugunsten von content.js
 * uebersprungen). content.js bleibt reiner Wortschatz, Grammatik lebt hier.
 *
 * Jedes Modul traegt group: "grammar" und ein band ("A0".."C2"). Schritt-Typen:
 *   - "explain": Lehrtext (title, text) mit optionalen `examples` [{he,translit,de}],
 *                die in der Zentralanzeige antippbar/vorlesbar sind.
 *   - "teach"/"quiz"/"pairquiz": wie in content.js, referenzieren bestehende Item-IDs.
 *   - "cloze": hebraeischer Satz mit Luecke (immer als ___). Felder:
 *                he, translit (mit ___), de (deutsche Bedeutung inkl. noetigem Kontext),
 *                options: 2-4 Stueck, GENAU eine mit correct:true, jede {he, translit},
 *                note (kurze Ausloesung nach dem Antworten, optional),
 *                itemId (optional, NUR fuer in content.js existierende Items -> recordAnswer).
 *   - "form": deutsche Aufgabe (prompt), waehle die richtige hebraeische Form. Felder:
 *                prompt, options (2-4, genau eine correct:true), note (optional).
 *
 * Regeln fuer cloze/form: die falschen Optionen sind ECHTE morphologische Kontraste
 * (falsches Genus/Numerus/Tempus/Binjan), nicht zufaellige Woerter. Niqqud entfaellt
 * in `he` (wie echte Schilder, ktiv male), Transliteration deutschfreundlich ("ch"
 * wie in "Bach", ' fuer Ajin/Kehllaut).
 *
 * WICHTIG: Grammatik-Erklaerungen sind sorgfaeltig erstellt, ein muttersprachliches
 * Gegenlesen (Niqqud, Transliteration, Register-Feinheiten) steht vor einem echten
 * Release noch aus.
 */
window.TACHELES_GRAMMAR = {
  version: 1,
  modules: [

    // ===================== Band A0 =====================
    {
      id: "mod_gram_genus", title: "Männlich oder weiblich?", emoji: "⚧", band: "A0", group: "grammar",
      sub: "Hebräisch kennt kein „das“ - jedes Wort ist m oder f.",
      steps: [
        { type: "explain", title: "Kein Neutrum",
          text: "Im Hebräischen ist jedes Nomen entweder männlich (m) oder weiblich (f), ein Neutrum wie das deutsche „das“ gibt es nicht. Bei Personen ist es meist logisch: ein Mann ist m, eine Frau ist f. Das Genus entscheidet später mit, wie Adjektive und Verben aussehen.",
          examples: [ { he: "איש", translit: "ish", de: "Mann (m)" }, { he: "אישה", translit: "isha", de: "Frau (f)" }, { he: "ילד", translit: "yeled", de: "Junge (m)" }, { he: "ילדה", translit: "yalda", de: "Mädchen (f)" } ] },
        { type: "explain", title: "Endungen -a und -et verraten oft „weiblich“",
          text: "Endet ein Wort auf ה (gesprochen -a) oder auf ת (-et), ist es meistens weiblich. Verlass dich aber nicht blind darauf: לילה (laila, Nacht) und אבא (aba, Papa) enden auf -a und sind trotzdem männlich. Die Endung ist eine gute Faustregel, kein Gesetz.",
          examples: [ { he: "מונית", translit: "monit", de: "Taxi (f)" }, { he: "דלת", translit: "delet", de: "Tür (f)" }, { he: "משפחה", translit: "mishpacha", de: "Familie (f)" }, { he: "לילה", translit: "laila", de: "Nacht - m trotz -a!" } ] },
        { type: "form", prompt: "„gut“, wenn du über eine Frau sprichst (sie ist gut)",
          options: [ { he: "טובה", translit: "tova", correct: true }, { he: "טוב", translit: "tov" } ],
          note: "Adjektive richten sich nach dem Nomen: -a für feminin, טובה (tova)." },
        { type: "form", prompt: "„groß“ für eine weibliche Sache",
          options: [ { he: "גדולה", translit: "gdola", correct: true }, { he: "גדול", translit: "gadol" } ],
          note: "גדול (gadol) ist die männliche, גדולה (gdola) die weibliche Form." },
        { type: "cloze", he: "הילדה ___", translit: "ha-yalda ___", de: "Das Mädchen ist klein.",
          options: [ { he: "קטנה", translit: "ktana", correct: true }, { he: "קטן", translit: "katan" } ],
          note: "ילדה (yalda) ist weiblich, also קטנה (ktana)." },
        { type: "cloze", he: "הילד ___", translit: "ha-yeled ___", de: "Der Junge ist groß.",
          options: [ { he: "גדול", translit: "gadol", correct: true }, { he: "גדולה", translit: "gdola" } ],
          note: "ילד (yeled) ist männlich, also גדול (gadol)." },
        { type: "form", prompt: "„müde“ für einen Mann (er ist müde)",
          options: [ { he: "עייף", translit: "ayef", correct: true }, { he: "עייפה", translit: "ayefa" } ],
          note: "Männlich עייף (ayef), weiblich עייפה (ayefa)." },
        { type: "form", prompt: "„müde“ für eine Frau (sie ist müde)",
          options: [ { he: "עייפה", translit: "ayefa", correct: true }, { he: "עייף", translit: "ayef" } ],
          note: "Die weibliche Form hängt -a an: עייפה (ayefa)." }
      ]
    },
    {
      id: "mod_gram_artikel", title: "Der Artikel ha- (ה)", emoji: "🅰", band: "A0", group: "grammar",
      sub: "Ein „ha“ vorn macht „das Ding“ - und „ein“ gibt es gar nicht.",
      steps: [
        { type: "explain", title: "„der/die/das“ = ha- vorne dran",
          text: "Es gibt nur einen bestimmten Artikel: die Vorsilbe ה (ha-). Sie wird direkt an das Wort geklebt. בית (bayit) heißt „Haus“, הבית (ha-bayit) „das Haus“. Der Artikel steht nie getrennt davor wie im Deutschen.",
          examples: [ { he: "בית ← הבית", translit: "bayit / ha-bayit", de: "Haus / das Haus" }, { he: "ספר ← הספר", translit: "sefer / ha-sefer", de: "Buch / das Buch" }, { he: "ילד ← הילד", translit: "yeled / ha-yeled", de: "Junge / der Junge" } ] },
        { type: "explain", title: "Es gibt kein „ein“",
          text: "Einen unbestimmten Artikel („ein/eine“) kennt das Hebräische nicht. קפה (kafe) heißt je nach Zusammenhang „Kaffee“ oder „ein Kaffee“. Du fügst also nichts hinzu, wenn du „ein“ sagen willst, du lässt es einfach weg.",
          examples: [ { he: "קפה", translit: "kafe", de: "Kaffee / ein Kaffee" }, { he: "רחוב", translit: "rechov", de: "Straße / eine Straße" }, { he: "מונית", translit: "monit", de: "Taxi / ein Taxi" } ] },
        { type: "form", prompt: "„das Haus“",
          options: [ { he: "הבית", translit: "ha-bayit", correct: true }, { he: "בית", translit: "bayit" } ],
          note: "ha- (ה) klebt vorne dran: הבית." },
        { type: "form", prompt: "„ein Kaffee“ (unbestimmt)",
          options: [ { he: "קפה", translit: "kafe", correct: true }, { he: "הקפה", translit: "ha-kafe" } ],
          note: "Für „ein“ gibt es kein Wort - einfach קפה, ohne ha-." },
        { type: "form", prompt: "„die Straße“",
          options: [ { he: "הרחוב", translit: "ha-rechov", correct: true }, { he: "רחוב", translit: "rechov" } ],
          note: "הרחוב = die (bestimmte) Straße." },
        { type: "cloze", he: "___ גדול", translit: "___ gadol", de: "Das Haus ist groß. (bestimmt: „das Haus“)",
          options: [ { he: "הבית", translit: "ha-bayit", correct: true }, { he: "בית", translit: "bayit" } ],
          note: "„Das Haus“ braucht den Artikel: הבית." },
        { type: "form", prompt: "„die Toilette / die Toiletten“ (auf dem Schild gesucht)",
          options: [ { he: "השירותים", translit: "ha-sherutim", correct: true }, { he: "שירותים", translit: "sherutim" } ],
          note: "Mit Artikel: השירותים." }
      ]
    },
    {
      id: "mod_gram_pronomen", title: "Ich, du, er, sie", emoji: "🧑", band: "A0", group: "grammar",
      sub: "Die Personalpronomen - und warum „du“ zwei Formen hat.",
      steps: [
        { type: "explain", title: "Die Grundformen",
          text: "Die wichtigsten Pronomen: אני (ani, ich), אתה (ata, du zu einem Mann), את (at, du zu einer Frau), הוא (hu, er), היא (hi, sie). Schon im „du“ musst du dich also entscheiden, ob du einen Mann oder eine Frau ansprichst.",
          examples: [ { he: "אני", translit: "ani", de: "ich" }, { he: "אתה", translit: "ata", de: "du (m)" }, { he: "את", translit: "at", de: "du (f)" }, { he: "הוא", translit: "hu", de: "er" }, { he: "היא", translit: "hi", de: "sie" } ] },
        { type: "explain", title: "Mehrzahl und Geschlecht",
          text: "Im Plural geht es weiter: אנחנו (anachnu, wir), אתם (atem, ihr - m oder gemischt), אתן (aten, ihr - nur Frauen), הם (hem, sie - m/gemischt), הן (hen, sie - nur Frauen). Bei gemischten Gruppen gewinnt immer die männliche Form.",
          examples: [ { he: "אנחנו", translit: "anachnu", de: "wir" }, { he: "אתם", translit: "atem", de: "ihr (m)" }, { he: "הם", translit: "hem", de: "sie (m)" }, { he: "הן", translit: "hen", de: "sie (f)" } ] },
        { type: "form", prompt: "„ich“",
          options: [ { he: "אני", translit: "ani", correct: true }, { he: "אתה", translit: "ata" } ],
          note: "אני (ani) = ich." },
        { type: "form", prompt: "„du“, zu einer Frau gesagt",
          options: [ { he: "את", translit: "at", correct: true }, { he: "אתה", translit: "ata" } ],
          note: "Zur Frau: את (at). Zum Mann: אתה (ata)." },
        { type: "form", prompt: "„du“, zu einem Mann gesagt",
          options: [ { he: "אתה", translit: "ata", correct: true }, { he: "את", translit: "at" } ],
          note: "Zum Mann: אתה (ata)." },
        { type: "form", prompt: "„er“",
          options: [ { he: "הוא", translit: "hu", correct: true }, { he: "היא", translit: "hi" } ],
          note: "הוא (hu) = er, היא (hi) = sie. Nur ein Buchstabe Unterschied." },
        { type: "form", prompt: "„wir“",
          options: [ { he: "אנחנו", translit: "anachnu", correct: true }, { he: "אתם", translit: "atem" } ],
          note: "אנחנו (anachnu) = wir." },
        { type: "cloze", he: "___ מדבר עברית", translit: "___ medaber ivrit", de: "Er spricht Hebräisch.",
          options: [ { he: "הוא", translit: "hu", correct: true }, { he: "היא", translit: "hi" } ],
          note: "מדבר (medaber) ist die männliche Verbform, passt zu הוא (hu). Bei היא hieße es medaberet." },
        { type: "form", prompt: "„sie“ - eine Gruppe aus mehreren Männern",
          options: [ { he: "הם", translit: "hem", correct: true }, { he: "הן", translit: "hen" } ],
          note: "הם (hem) für Männer/gemischt, הן (hen) nur für Frauen." }
      ]
    },

    // ===================== Band A1 =====================
    {
      id: "mod_gram_praesens", title: "Präsens: vier Formen", emoji: "🏃", band: "A1", group: "grammar",
      sub: "Ein Verb, vier Gesichter: m/f, Einzahl/Mehrzahl.",
      steps: [
        { type: "explain", title: "Vier Formen statt sechs",
          text: "Im Präsens hat ein Verb nur vier Formen - je nach Geschlecht und Zahl, nicht nach Person. „Ich, du, er“ (männlich, Einzahl) teilen sich also eine Form. Ein eigenes Wort für „sein“ gibt es im Präsens nicht: אני לומד heißt schon „ich lerne“.",
          examples: [ { he: "לומד", translit: "lomed", de: "lernt (m, Einzahl)" }, { he: "לומדת", translit: "lomedet", de: "lernt (f, Einzahl)" }, { he: "לומדים", translit: "lomdim", de: "lernen (m, Mehrzahl)" }, { he: "לומדות", translit: "lomdot", de: "lernen (f, Mehrzahl)" } ] },
        { type: "explain", title: "Das Muster erkennen",
          text: "Die weibliche Form hängt meist -et oder -a an, die Mehrzahl -im (m) bzw. -ot (f). Wenn du das Muster einmal hast, kannst du es auf viele Verben übertragen.",
          examples: [ { he: "שותה / שותים", translit: "shote / shotim", de: "trinkt (m) / trinken (m-pl)" }, { he: "עובד / עובדת", translit: "oved / ovedet", de: "arbeitet (m) / (f)" }, { he: "רואה / רואים", translit: "ro'e / ro'im", de: "sieht / sehen (m-pl)" } ] },
        { type: "cloze", he: "אני ___ קפה", translit: "ani ___ kafe", de: "Ich trinke Kaffee. (ein Mann spricht)", itemId: "shote",
          options: [ { he: "שותה", translit: "shote", correct: true }, { he: "שותים", translit: "shotim" } ],
          note: "Einzahl männlich: שותה (shote). שותים (shotim) wäre Mehrzahl." },
        { type: "cloze", he: "היא ___ עברית", translit: "hi ___ ivrit", de: "Sie lernt Hebräisch.",
          options: [ { he: "לומדת", translit: "lomedet", correct: true }, { he: "לומד", translit: "lomed" } ],
          note: "היא (sie) verlangt die weibliche Form לומדת (lomedet)." },
        { type: "cloze", he: "הם ___ בעיר", translit: "hem ___ ba-ir", de: "Sie (Männer) wohnen in der Stadt.",
          options: [ { he: "גרים", translit: "garim", correct: true }, { he: "גר", translit: "gar" } ],
          note: "Mehrzahl männlich: גרים (garim)." },
        { type: "cloze", he: "אני ___ לעבודה", translit: "ani ___ la-avoda", de: "Ich gehe zur Arbeit. (ein Mann spricht)", itemId: "holech",
          options: [ { he: "הולך", translit: "holech", correct: true }, { he: "הולכת", translit: "holechet" } ],
          note: "Männlich הולך (holech), weiblich wäre הולכת (holechet)." },
        { type: "form", prompt: "„sie arbeitet“ (eine Frau, Einzahl)",
          options: [ { he: "עובדת", translit: "ovedet", correct: true }, { he: "עובד", translit: "oved" } ],
          note: "Weibliche Einzahl: עובדת (ovedet)." },
        { type: "cloze", he: "אנחנו ___ סרט", translit: "anachnu ___ seret", de: "Wir sehen einen Film.",
          options: [ { he: "רואים", translit: "ro'im", correct: true }, { he: "רואה", translit: "ro'e" } ],
          note: "„Wir“ ist Mehrzahl: רואים (ro'im)." },
        { type: "quiz", itemId: "shote", distractorIds: ["ochel_v"] }
      ]
    },
    {
      id: "mod_gram_besitz", title: "Besitz mit „shel“", emoji: "🔑", band: "A1", group: "grammar",
      sub: "„von mir“, „von dir“: wie du sagst, wem etwas gehört.",
      steps: [
        { type: "explain", title: "shel = „von / gehört“",
          text: "Besitz drückst du mit של (shel, „von“) aus: הספר שלי (ha-sefer sheli) heißt wörtlich „das Buch von mir“, also „mein Buch“. Das besessene Ding bekommt dabei den Artikel ha-.",
          examples: [ { he: "הספר שלי", translit: "ha-sefer sheli", de: "mein Buch" }, { he: "הבית שלנו", translit: "ha-bayit shelanu", de: "unser Haus" }, { he: "המפתח שלו", translit: "ha-mafteach shelo", de: "sein Schlüssel" } ] },
        { type: "explain", title: "Die Possessiv-Reihe",
          text: "shel verschmilzt mit der Person: שלי (sheli, mein), שלך (shelcha, dein zu m / shelach, dein zu f - gleich geschrieben!), שלו (shelo, sein), שלה (shela, ihr), שלנו (shelanu, unser), שלכם (shelachem, euer), שלהם (shelahem, ihr/deren).",
          examples: [ { he: "שלי", translit: "sheli", de: "mein" }, { he: "שלך", translit: "shelcha / shelach", de: "dein (m / f)" }, { he: "שלו", translit: "shelo", de: "sein" }, { he: "שלה", translit: "shela", de: "ihr" } ] },
        { type: "form", prompt: "„mein“ (mein Buch)",
          options: [ { he: "שלי", translit: "sheli", correct: true }, { he: "שלך", translit: "shelcha" } ],
          note: "שלי (sheli) = mein." },
        { type: "form", prompt: "„dein“, zu einem Mann gesagt",
          options: [ { he: "שלך", translit: "shelcha", correct: true }, { he: "שלי", translit: "sheli" } ],
          note: "שלך: als shelcha (m) oder shelach (f) - gleich geschrieben, Aussprache entscheidet." },
        { type: "cloze", he: "הספר ___", translit: "ha-sefer ___", de: "das Buch gehört mir (mein Buch)",
          options: [ { he: "שלי", translit: "sheli", correct: true }, { he: "שלו", translit: "shelo" } ],
          note: "„mein“ = שלי (sheli); שלו (shelo) wäre „sein“." },
        { type: "cloze", he: "הבית ___", translit: "ha-bayit ___", de: "unser Haus",
          options: [ { he: "שלנו", translit: "shelanu", correct: true }, { he: "שלכם", translit: "shelachem" } ],
          note: "„unser“ = שלנו (shelanu); שלכם (shelachem) wäre „euer“." },
        { type: "form", prompt: "„ihr“ (gehört ihr, einer Frau)",
          options: [ { he: "שלה", translit: "shela", correct: true }, { he: "שלו", translit: "shelo" } ],
          note: "שלה (shela) = ihr (f), שלו (shelo) = sein (m)." },
        { type: "cloze", he: "המפתח ___", translit: "ha-mafteach ___", de: "sein Schlüssel",
          options: [ { he: "שלו", translit: "shelo", correct: true }, { he: "שלה", translit: "shela" } ],
          note: "„sein“ = שלו (shelo)." }
      ]
    },
    {
      id: "mod_gram_fragen", title: "Fragen stellen", emoji: "❓", band: "A1", group: "grammar",
      sub: "Fragewörter und wie ein hebräischer Fragesatz gebaut ist.",
      steps: [
        { type: "explain", title: "Die Fragewörter",
          text: "Die wichtigsten Fragewörter: מה (ma, was), מי (mi, wer), איפה (eifo, wo), מתי (matai, wann), כמה (kama, wie viel), למה (lama, warum), איך (eich, wie). Sie stehen fast immer am Anfang der Frage.",
          examples: [ { he: "מה", translit: "ma", de: "was" }, { he: "מי", translit: "mi", de: "wer" }, { he: "איפה", translit: "eifo", de: "wo" }, { he: "כמה", translit: "kama", de: "wie viel" } ] },
        { type: "explain", title: "Ja/Nein-Fragen: nur die Betonung",
          text: "Für eine Ja/Nein-Frage änderst du die Wortstellung nicht wie im Deutschen. אתה בא (ata ba) heißt „du kommst“, mit fragender Betonung wird daraus „kommst du?“. Formell kann man האם (ha'im) voranstellen, im Alltag reicht die Stimme.",
          examples: [ { he: "אתה בא?", translit: "ata ba?", de: "Kommst du?" }, { he: "יש קפה?", translit: "yesh kafe?", de: "Gibt es Kaffee?" }, { he: "זה טוב?", translit: "ze tov?", de: "Ist das gut?" } ] },
        { type: "form", prompt: "Fragewort „wo?“",
          options: [ { he: "איפה", translit: "eifo", correct: true }, { he: "מתי", translit: "matai" } ],
          note: "איפה (eifo) = wo; מתי (matai) = wann." },
        { type: "form", prompt: "Fragewort „was?“",
          options: [ { he: "מה", translit: "ma", correct: true }, { he: "מי", translit: "mi" } ],
          note: "מה (ma) = was; מי (mi) = wer." },
        { type: "form", prompt: "Fragewort „wann?“",
          options: [ { he: "מתי", translit: "matai", correct: true }, { he: "כמה", translit: "kama" } ],
          note: "מתי (matai) = wann; כמה (kama) = wie viel." },
        { type: "cloze", he: "___ אתה גר?", translit: "___ ata gar?", de: "Wo wohnst du?",
          options: [ { he: "איפה", translit: "eifo", correct: true }, { he: "מתי", translit: "matai" } ],
          note: "Ort erfragt man mit איפה (eifo)." },
        { type: "cloze", he: "___ עולה הקפה?", translit: "___ ole ha-kafe?", de: "Wie viel kostet der Kaffee?",
          options: [ { he: "כמה", translit: "kama", correct: true }, { he: "מה", translit: "ma" } ],
          note: "Preis/Menge: כמה (kama)." },
        { type: "cloze", he: "___ קוראים לך?", translit: "___ korim lecha?", de: "Wie heißt du? (wörtlich: wie ruft man dich?)",
          options: [ { he: "איך", translit: "eich", correct: true }, { he: "למה", translit: "lama" } ],
          note: "Feste Wendung mit איך (eich): „eich korim lecha“." },
        { type: "quiz", itemId: "eifo", distractorIds: ["ma"] }
      ]
    },
    {
      id: "mod_gram_plural", title: "Mehrzahl: -im und -ot", emoji: "➕", band: "A1", group: "grammar",
      sub: "Die zwei Grundendungen - und die fiesen Ausnahmen.",
      steps: [
        { type: "explain", title: "Zwei Endungen",
          text: "Der Plural hat zwei Grundendungen: -ים (-im), meist bei männlichen Wörtern, und -ות (-ot), meist bei weiblichen. ילד (yeled) wird zu ילדים (yeladim), ילדה (yalda) zu ילדות (yeladot).",
          examples: [ { he: "ילד ← ילדים", translit: "yeled / yeladim", de: "Junge / Jungen" }, { he: "ילדה ← ילדות", translit: "yalda / yeladot", de: "Mädchen / Mädchen" }, { he: "ספר ← ספרים", translit: "sefer / sfarim", de: "Buch / Bücher" } ] },
        { type: "explain", title: "Ausnahmen, die man kennen muss",
          text: "Ein paar Alltagswörter halten sich nicht an die Regel: בית (bayit) wird zu בתים (batim), איש (ish) zu אנשים (anashim), אישה (isha) zu נשים (nashim), שנה (shana) zu שנים (shanim). Und שולחן (shulchan) ist männlich, nimmt aber -ot: שולחנות (shulchanot).",
          examples: [ { he: "בית ← בתים", translit: "bayit / batim", de: "Haus / Häuser" }, { he: "איש ← אנשים", translit: "ish / anashim", de: "Mann / Leute" }, { he: "שולחן ← שולחנות", translit: "shulchan / shulchanot", de: "Tisch / Tische (m, aber -ot!)" } ] },
        { type: "form", prompt: "Mehrzahl von בית (Haus)",
          options: [ { he: "בתים", translit: "batim", correct: true }, { he: "ביתים", translit: "beitim" } ],
          note: "Unregelmäßig: בתים (batim), nicht *beitim." },
        { type: "form", prompt: "Mehrzahl von איש (Mann) - „Leute“",
          options: [ { he: "אנשים", translit: "anashim", correct: true }, { he: "אישים", translit: "ishim" } ],
          note: "Unregelmäßig: אנשים (anashim)." },
        { type: "cloze", he: "בעיר יש הרבה ___", translit: "ba-ir yesh harbe ___", de: "In der Stadt gibt es viele Häuser.",
          options: [ { he: "בתים", translit: "batim", correct: true }, { he: "ביתים", translit: "beitim" } ],
          note: "Plural von bayit ist batim." },
        { type: "form", prompt: "Mehrzahl von שולחן (Tisch, männlich)",
          options: [ { he: "שולחנות", translit: "shulchanot", correct: true }, { he: "שולחנים", translit: "shulchanim" } ],
          note: "Männlich, nimmt aber -ot: שולחנות (shulchanot)." },
        { type: "form", prompt: "Mehrzahl von שנה (Jahr)",
          options: [ { he: "שנים", translit: "shanim", correct: true }, { he: "שנות", translit: "shanot" } ],
          note: "Weiblich, nimmt aber -im: שנים (shanim). שנות nur in Verbindungen (shnot-)." },
        { type: "form", prompt: "Mehrzahl von אישה (Frau)",
          options: [ { he: "נשים", translit: "nashim", correct: true }, { he: "אישים", translit: "ishim" } ],
          note: "Ganz unregelmäßig: נשים (nashim)." }
      ]
    },

    // ===================== Band A2 =====================
    {
      id: "mod_gram_vergangenheit", title: "Vergangenheit", emoji: "⏪", band: "A2", group: "grammar",
      sub: "Endungen ans Verb - das Grundparadigma (katav).",
      steps: [
        { type: "explain", title: "Endungen statt Hilfsverb",
          text: "Die Vergangenheit bildest du mit Endungen am Verbstamm, kein „haben/sein“ nötig. Am Beispiel כתב (k-t-v, schreiben): כתבתי (katavti, ich schrieb), כתבת (katavta, du m / katavt, du f), כתב (katav, er), כתבה (katva, sie), כתבנו (katavnu, wir), כתבו (katvu, sie).",
          examples: [ { he: "כתבתי", translit: "katavti", de: "ich schrieb" }, { he: "כתב", translit: "katav", de: "er schrieb" }, { he: "כתבה", translit: "katva", de: "sie schrieb" }, { he: "כתבו", translit: "katvu", de: "sie schrieben" } ] },
        { type: "explain", title: "„Ich“ endet auf -ti",
          text: "Die Ich-Form endet immer auf -תי (-ti). Das kennst du schon aus dem Wortschatz: הלכתי (halachti, ich ging), אכלתי (achalti, ich aß), אמרתי (amarti, ich sagte). Wenn du am Ende ein -ti hörst, ist fast immer „ich“ und Vergangenheit gemeint.",
          examples: [ { he: "הלכתי", translit: "halachti", de: "ich ging" }, { he: "אכלתי", translit: "achalti", de: "ich aß" }, { he: "אמרתי", translit: "amarti", de: "ich sagte" } ] },
        { type: "cloze", he: "אתמול ___ לים", translit: "etmol ___ la-yam", de: "Gestern ging ich ans Meer. (ich)", itemId: "halachti",
          options: [ { he: "הלכתי", translit: "halachti", correct: true }, { he: "הלך", translit: "halach" } ],
          note: "Ich-Form: הלכתי (halachti). הלך (halach) wäre „er ging“." },
        { type: "cloze", he: "אני ___ פלאפל אתמול", translit: "ani ___ falafel etmol", de: "Ich aß gestern Falafel.", itemId: "achalti",
          options: [ { he: "אכלתי", translit: "achalti", correct: true }, { he: "אוכל", translit: "ochel" } ],
          note: "Vergangenheit: אכלתי (achalti). אוכל (ochel) wäre Präsens „ich esse“." },
        { type: "cloze", he: "היא ___ קפה", translit: "hi ___ kafe", de: "Sie trank Kaffee.",
          options: [ { he: "שתתה", translit: "shatta", correct: true }, { he: "שתה", translit: "shata" } ],
          note: "Sie: שתתה (shatta). שתה (shata) wäre „er trank“." },
        { type: "form", prompt: "„du hast geschrieben“ (zu einem Mann)",
          options: [ { he: "כתבת", translit: "katavta", correct: true }, { he: "כתבתי", translit: "katavti" } ],
          note: "Du-Form (m): כתבת (katavta). Mit -ti wäre es „ich“." },
        { type: "cloze", he: "הם ___ הביתה", translit: "hem ___ ha-bayta", de: "Sie gingen nach Hause.",
          options: [ { he: "הלכו", translit: "halchu", correct: true }, { he: "הלך", translit: "halach" } ],
          note: "Mehrzahl: הלכו (halchu)." },
        { type: "cloze", he: "אנחנו ___ בתל אביב", translit: "anachnu ___ be-tel aviv", de: "Wir wohnten in Tel Aviv.",
          options: [ { he: "גרנו", translit: "garnu", correct: true }, { he: "גר", translit: "gar" } ],
          note: "Wir-Form endet auf -nu: גרנו (garnu)." }
      ]
    },
    {
      id: "mod_gram_zukunft", title: "Zukunft", emoji: "⏩", band: "A2", group: "grammar",
      sub: "Die Zukunft kommt von vorn: e-, ti-, yi-, ni-.",
      steps: [
        { type: "explain", title: "Die Zukunft kommt von vorn",
          text: "Anders als die Vergangenheit baut sich die Zukunft vor allem mit VORsilben: א (e-, ich), ת (ti-, du und sie-f), י (yi-, er), נ (ni-, wir). Einige Personen bekommen zusätzlich eine Endung (z. B. תכתבי tichtevi, du-f; תכתבו tichtevu, ihr) – die hebst du dir für später auf. Aus dem Wortschatz kennst du schon אלך (elech, ich werde gehen), אשתה (eshte, ich werde trinken), אבוא (avo, ich werde kommen).",
          examples: [ { he: "אלך", translit: "elech", de: "ich werde gehen" }, { he: "אשתה", translit: "eshte", de: "ich werde trinken" }, { he: "יהיה", translit: "yihye", de: "es wird sein" } ] },
        { type: "explain", title: "Ein Verb durch die Personen",
          text: "Am Beispiel כתב (schreiben): אכתוב (ektov, ich), תכתוב (tichtov, du m / sie-f), יכתוב (yichtov, er), נכתוב (nichtov, wir). Merke: das ת steht für „du“ genauso wie für „sie“ (f), das י nur für „er“.",
          examples: [ { he: "אכתוב", translit: "ektov", de: "ich werde schreiben" }, { he: "תכתוב", translit: "tichtov", de: "du wirst schreiben (m)" }, { he: "יכתוב", translit: "yichtov", de: "er wird schreiben" }, { he: "נכתוב", translit: "nichtov", de: "wir werden schreiben" } ] },
        { type: "cloze", he: "מחר ___ לעבודה", translit: "machar ___ la-avoda", de: "Morgen werde ich zur Arbeit gehen.", itemId: "elech",
          options: [ { he: "אלך", translit: "elech", correct: true }, { he: "הלכתי", translit: "halachti" } ],
          note: "Zukunft, ich: אלך (elech). הלכתי wäre Vergangenheit." },
        { type: "cloze", he: "הוא ___ קפה", translit: "hu ___ kafe", de: "Er wird Kaffee trinken.",
          options: [ { he: "ישתה", translit: "yishte", correct: true }, { he: "אשתה", translit: "eshte" } ],
          note: "„er“ nimmt die Vorsilbe י: ישתה (yishte). אשתה wäre „ich“." },
        { type: "cloze", he: "אתה ___ מחר?", translit: "ata ___ machar?", de: "Wirst du morgen kommen? (zu einem Mann)",
          options: [ { he: "תבוא", translit: "tavo", correct: true }, { he: "אבוא", translit: "avo" } ],
          note: "„du“ nimmt ת: תבוא (tavo). אבוא wäre „ich“." },
        { type: "form", prompt: "„ich werde kaufen“",
          options: [ { he: "אקנה", translit: "ekne", correct: true }, { he: "יקנה", translit: "yikne" } ],
          note: "Ich-Vorsilbe א: אקנה (ekne). יקנה wäre „er“." },
        { type: "cloze", he: "הכל ___ בסדר", translit: "ha-kol ___ beseder", de: "Alles wird gut.", itemId: "yihye",
          options: [ { he: "יהיה", translit: "yihye", correct: true }, { he: "היה", translit: "haya" } ],
          note: "Zukunft: יהיה (yihye). היה (haya) wäre „war“." },
        { type: "cloze", he: "אנחנו ___ מחר", translit: "anachnu ___ machar", de: "Wir werden morgen kommen.",
          options: [ { he: "נבוא", translit: "navo", correct: true }, { he: "אבוא", translit: "avo" } ],
          note: "„wir“ nimmt נ: נבוא (navo)." }
      ]
    },
    {
      id: "mod_gram_praepositionen", title: "be-, le-, mi- & Suffixe", emoji: "📍", band: "A2", group: "grammar",
      sub: "Kleine Vorsilben - und wie sie mit Pronomen verschmelzen.",
      steps: [
        { type: "explain", title: "Drei angeklebte Präpositionen",
          text: "Drei häufige Präpositionen klebt man direkt ans Wort: ב (be-, in/mit), ל (le-, zu/für), מ (mi-, von/aus). בתל אביב (be-tel aviv, in Tel Aviv), לעבודה (le-avoda, zur Arbeit), מברלין (mi-berlin, aus Berlin). Trifft be-/le- auf den Artikel ha-, verschmelzen sie: be+ha wird ba- (בבית, ba-bayit, im Haus), le+ha wird la- (לעבודה, la-avoda, zur Arbeit).",
          examples: [ { he: "בבית", translit: "ba-bayit", de: "im Haus" }, { he: "לעבודה", translit: "la-avoda", de: "zur Arbeit" }, { he: "מברלין", translit: "mi-berlin", de: "aus Berlin" } ] },
        { type: "explain", title: "Mit Pronomen verschmolzen",
          text: "Mit einem Pronomen wird ל zu einer eigenen kleinen Reihe: לי (li, mir), לך (lecha/lach, dir m/f), לו (lo, ihm), לה (la, ihr), לנו (lanu, uns). Das steckt auch in „יש לי“ (yesh li, ich habe - wörtlich „es gibt mir“).",
          examples: [ { he: "יש לי", translit: "yesh li", de: "ich habe" }, { he: "לו", translit: "lo", de: "ihm" }, { he: "לה", translit: "la", de: "ihr" }, { he: "ממני", translit: "mimeni", de: "von mir" } ] },
        { type: "form", prompt: "„mir / zu mir“",
          options: [ { he: "לי", translit: "li", correct: true }, { he: "לו", translit: "lo" } ],
          note: "לי (li) = mir; לו (lo) = ihm." },
        { type: "form", prompt: "„ihm / zu ihm“",
          options: [ { he: "לו", translit: "lo", correct: true }, { he: "לה", translit: "la" } ],
          note: "לו (lo) = ihm; לה (la) = ihr." },
        { type: "cloze", he: "יש ___ שאלה", translit: "yesh ___ she'ela", de: "Ich habe eine Frage. (yesh li)",
          options: [ { he: "לי", translit: "li", correct: true }, { he: "לו", translit: "lo" } ],
          note: "„ich habe“ = yesh li, mit לי (li)." },
        { type: "cloze", he: "אני נותן ___ את הספר", translit: "ani noten ___ et ha-sefer", de: "Ich gebe ihr das Buch.",
          options: [ { he: "לה", translit: "la", correct: true }, { he: "לו", translit: "lo" } ],
          note: "„ihr“ = לה (la)." },
        { type: "form", prompt: "„von mir / aus mir“",
          options: [ { he: "ממני", translit: "mimeni", correct: true }, { he: "ממך", translit: "mimcha" } ],
          note: "מ mit „ich“: ממני (mimeni)." },
        { type: "form", prompt: "„dir / zu dir“, zu einer Frau",
          options: [ { he: "לך", translit: "lach", correct: true }, { he: "לי", translit: "li" } ],
          note: "לך als lach (f) oder lecha (m) - gleich geschrieben." },
        { type: "cloze", he: "אני נוסע ___ ירושלים", translit: "ani nose'a ___ yerushalayim", de: "Ich fahre nach Jerusalem. (Richtung: „nach/zu“)",
          options: [ { he: "ל", translit: "le-", correct: true }, { he: "מ", translit: "mi-" } ],
          note: "Richtung „nach/zu“ = ל (le-); מ (mi-) wäre „von/aus“." }
      ]
    },
    {
      id: "mod_gram_adjektiv", title: "Adjektiv-Kongruenz", emoji: "🎨", band: "A2", group: "grammar",
      sub: "Das Adjektiv passt sich dem Nomen an - in allem.",
      steps: [
        { type: "explain", title: "Das Adjektiv folgt und passt sich an",
          text: "Das Adjektiv steht HINTER dem Nomen und richtet sich nach ihm in Geschlecht und Zahl: ילד טוב (yeled tov, guter Junge), ילדה טובה (yalda tova), ילדים טובים (yeladim tovim), ילדות טובות (yeladot tovot).",
          examples: [ { he: "ילד טוב", translit: "yeled tov", de: "guter Junge" }, { he: "ילדה טובה", translit: "yalda tova", de: "gutes Mädchen" }, { he: "ילדים טובים", translit: "yeladim tovim", de: "gute Jungen" }, { he: "ילדות טובות", translit: "yeladot tovot", de: "gute Mädchen" } ] },
        { type: "explain", title: "Auch die Bestimmtheit muss passen",
          text: "Ist das Nomen bestimmt (mit ha-), bekommt das Adjektiv AUCH ein ha-: ילד טוב (ein guter Junge), aber הילד הטוב (ha-yeled ha-tov, der gute Junge). Beide Wörter tragen dann den Artikel.",
          examples: [ { he: "בית גדול", translit: "bayit gadol", de: "ein großes Haus" }, { he: "הבית הגדול", translit: "ha-bayit ha-gadol", de: "das große Haus" } ] },
        { type: "form", prompt: "„ein großes Haus“ (בית ist männlich)",
          options: [ { he: "בית גדול", translit: "bayit gadol", correct: true }, { he: "בית גדולה", translit: "bayit gdola" } ],
          note: "bayit (m) → gadol (m). gdola wäre weiblich." },
        { type: "cloze", he: "ילדה ___", translit: "yalda ___", de: "ein kleines Mädchen",
          options: [ { he: "קטנה", translit: "ktana", correct: true }, { he: "קטן", translit: "katan" } ],
          note: "yalda (f) → ktana (f)." },
        { type: "cloze", he: "אנשים ___", translit: "anashim ___", de: "gute Leute (Männer)",
          options: [ { he: "טובים", translit: "tovim", correct: true }, { he: "טוב", translit: "tov" } ],
          note: "Mehrzahl männlich → tovim." },
        { type: "form", prompt: "„die große Stadt“ (mit Artikel; עיר ist weiblich)",
          options: [ { he: "העיר הגדולה", translit: "ha-ir ha-gdola", correct: true }, { he: "העיר גדולה", translit: "ha-ir gdola" } ],
          note: "Bei Bestimmtheit tragen BEIDE Wörter ha-: העיר הגדולה." },
        { type: "cloze", he: "ספרים ___", translit: "sfarim ___", de: "neue Bücher",
          options: [ { he: "חדשים", translit: "chadashim", correct: true }, { he: "חדשות", translit: "chadashot" } ],
          note: "sefer ist männlich, Plural sfarim → chadashim. חדשות wäre feminin (oder „Nachrichten“)." },
        { type: "cloze", he: "מכונית ___", translit: "mechonit ___", de: "ein rotes Auto (mechonit ist weiblich)",
          options: [ { he: "אדומה", translit: "aduma", correct: true }, { he: "אדום", translit: "adom" } ],
          note: "mechonit (f) → aduma (f)." },
        { type: "pairquiz", itemId: "gadol", pairId: "katan" }
      ]
    },

    // ===================== Band B1 =====================
    {
      id: "mod_gram_binjanim", title: "Binjanim erkennen", emoji: "🏗", band: "B1", group: "grammar",
      sub: "Verben kommen in „Bauformen“ - pa'al, pi'el, hif'il.",
      steps: [
        { type: "explain", title: "Verben haben Bauformen",
          text: "Hebräische Verben sind aus einer Wurzel (meist drei Buchstaben) plus einem Muster gebaut, dem Binjan. Die drei häufigsten: pa'al (die Grundform, z. B. כותב kotev, הולך holech), pi'el (oft intensiv/verursachend, z. B. מדבר medaber, מלמד melamed) und hif'il (oft veranlassen, z. B. מזמין mazmin).",
          examples: [ { he: "כותב", translit: "kotev", de: "schreibt (pa'al)" }, { he: "מדבר", translit: "medaber", de: "spricht (pi'el)" }, { he: "מזמין", translit: "mazmin", de: "lädt ein / bestellt (hif'il)" } ] },
        { type: "explain", title: "Der Trick im Präsens: das מ",
          text: "Im Präsens hilft ein einfaches Merkmal: pa'al beginnt OHNE Vorsilbe (כותב, הולך), während pi'el, hif'il (und weitere) mit מ (m-) anfangen (מדבר, מזמין, מלמד). Hörst du vorn ein „me/ma“, ist es kein pa'al.",
          examples: [ { he: "לומד", translit: "lomed", de: "lernt (pa'al, kein מ)" }, { he: "מלמד", translit: "melamed", de: "lehrt/bringt bei (pi'el, mit מ)" }, { he: "מזמין", translit: "mazmin", de: "bestellt (hif'il, mit מ)" } ] },
        { type: "form", prompt: "Welche Form ist pi'el („spricht“)?",
          options: [ { he: "מדבר", translit: "medaber", correct: true }, { he: "כותב", translit: "kotev" } ],
          note: "מדבר (medaber) ist pi'el (mit מ); כותב (kotev) ist pa'al." },
        { type: "form", prompt: "Welche Form ist pa'al („lernt“)?",
          options: [ { he: "לומד", translit: "lomed", correct: true }, { he: "מלמד", translit: "melamed" } ],
          note: "לומד (lomed) = lernt (pa'al). מלמד (melamed) = bringt bei (pi'el)." },
        { type: "cloze", he: "המורה ___ עברית", translit: "ha-more ___ ivrit", de: "Der Lehrer bringt Hebräisch bei. (pi'el)",
          options: [ { he: "מלמד", translit: "melamed", correct: true }, { he: "לומד", translit: "lomed" } ],
          note: "„beibringen/lehren“ = מלמד (melamed, pi'el). לומד (lomed) hieße „lernt“." },
        { type: "form", prompt: "Welche Form ist hif'il („bestellt / lädt ein“)?",
          options: [ { he: "מזמין", translit: "mazmin", correct: true }, { he: "זמן", translit: "zman" } ],
          note: "מזמין (mazmin) ist das Verb (hif'il); זמן (zman) ist das Nomen „Zeit“." },
        { type: "cloze", he: "אני ___ מונית", translit: "ani ___ monit", de: "Ich bestelle ein Taxi. (hif'il)",
          options: [ { he: "מזמין", translit: "mazmin", correct: true }, { he: "מזומן", translit: "mezuman" } ],
          note: "מזמין (mazmin) = bestellen/einladen. מזומן (mezuman) = „bereit/bar“ (andere Form derselben Wurzel)." }
      ]
    },
    {
      id: "mod_gram_smichut", title: "Smichut (Verbindung)", emoji: "🔗", band: "B1", group: "grammar",
      sub: "Zwei Nomen zusammengeklebt: „Haus-des-Buchs“ = Schule.",
      steps: [
        { type: "explain", title: "Zwei Nomen, eine Einheit",
          text: "Der Smichut verbindet zwei Nomen zu „X von Y“, ohne Wörtchen dazwischen. בית ספר (beit sefer) ist wörtlich „Haus-des-Buchs“ und meint „Schule“. Das erste Nomen ändert oft leicht seine Form (bayit → beit).",
          examples: [ { he: "בית ספר", translit: "beit sefer", de: "Schule (Haus-des-Buchs)" }, { he: "ראש ממשלה", translit: "rosh memshala", de: "Premierminister (Kopf-der-Regierung)" }, { he: "יום הולדת", translit: "yom huledet", de: "Geburtstag (Tag-der-Geburt)" } ] },
        { type: "explain", title: "Der Artikel wandert nach hinten",
          text: "Willst du „die Schule“ sagen, kommt das ha- NICHT vor das erste Wort, sondern vor das zweite: בית הספר (beit ha-sefer). Das kennst du schon aus dem Wortschatz: בית חולים (beit cholim, Krankenhaus) und שדה תעופה (sde teufa, Flughafen) sind auch Smichut.",
          examples: [ { he: "בית הספר", translit: "beit ha-sefer", de: "die Schule" }, { he: "בית חולים", translit: "beit cholim", de: "Krankenhaus" }, { he: "שדה תעופה", translit: "sde teufa", de: "Flughafen" } ] },
        { type: "form", prompt: "„eine Schule“ (unbestimmt)",
          options: [ { he: "בית ספר", translit: "beit sefer", correct: true }, { he: "הבית ספר", translit: "ha-bayit sefer" } ],
          note: "Ohne Artikel: בית ספר. Ein ha- vorne wäre falsch." },
        { type: "form", prompt: "„die Schule“ (bestimmt)",
          options: [ { he: "בית הספר", translit: "beit ha-sefer", correct: true }, { he: "הבית ספר", translit: "ha-bayit sefer" } ],
          note: "Der Artikel steht am zweiten Wort: בית הספר." },
        { type: "form", prompt: "„ein Premierminister“ (Kopf-der-Regierung)",
          options: [ { he: "ראש ממשלה", translit: "rosh memshala", correct: true }, { he: "הראש ממשלה", translit: "ha-rosh memshala" } ],
          note: "Smichut ohne Artikel: ראש ממשלה. „Der Premier“ wäre ראש הממשלה." },
        { type: "cloze", he: "הלכתי ל___ חולים", translit: "halachti le-___ cholim", de: "Ich ging ins Krankenhaus (beit cholim).",
          options: [ { he: "בית", translit: "beit", correct: true }, { he: "בתי", translit: "batei" } ],
          note: "Einzahl-Verbindung: בית חולים. בתי wäre die Mehrzahl-Verbindung (batei-)." },
        { type: "form", prompt: "„Geburtstag“ (Tag-der-Geburt)",
          options: [ { he: "יום הולדת", translit: "yom huledet", correct: true }, { he: "היום הולדת", translit: "ha-yom huledet" } ],
          note: "Feste Verbindung ohne Artikel vorn: יום הולדת." }
      ]
    },
    {
      id: "mod_gram_et", title: "Objektmarker „et“", emoji: "🎯", band: "B1", group: "grammar",
      sub: "Vor bestimmten Objekten steht ein kleines Wort: את.",
      steps: [
        { type: "explain", title: "et markiert das bestimmte Objekt",
          text: "Vor einem BESTIMMTEN direkten Objekt steht את (et) - ein Wort ohne eigene Übersetzung. אני רואה את הילד (ani ro'e et ha-yeled) = „Ich sehe den Jungen“. Ist das Objekt unbestimmt, fällt et weg: אני רואה ילד (ich sehe einen Jungen).",
          examples: [ { he: "רואה את הילד", translit: "ro'e et ha-yeled", de: "sieht den Jungen (bestimmt)" }, { he: "רואה ילד", translit: "ro'e yeled", de: "sieht einen Jungen (kein et)" } ] },
        { type: "explain", title: "et + Pronomen",
          text: "Mit einem Pronomen verschmilzt et zu einer eigenen Reihe: אותי (oti, mich), אותך (otcha/otach, dich m/f), אותו (oto, ihn), אותה (ota, sie), אותנו (otanu, uns), אותם (otam, sie/pl). „Ich liebe dich“ = אני אוהב אותך (ani ohev otach).",
          examples: [ { he: "אותי", translit: "oti", de: "mich" }, { he: "אותך", translit: "otcha / otach", de: "dich (m/f)" }, { he: "אותו", translit: "oto", de: "ihn" }, { he: "אותה", translit: "ota", de: "sie" } ] },
        { type: "cloze", he: "אני רואה ___ הילד", translit: "ani ro'e ___ ha-yeled", de: "Ich sehe den Jungen.",
          options: [ { he: "את", translit: "et", correct: true }, { he: "ל", translit: "le-" } ],
          note: "Vor bestimmtem Objekt (ha-yeled) steht את (et)." },
        { type: "form", prompt: "„einen Jungen sehen“ (unbestimmt) - was ist richtig?",
          options: [ { he: "רואה ילד", translit: "ro'e yeled", correct: true }, { he: "רואה את ילד", translit: "ro'e et yeled" } ],
          note: "Vor unbestimmtem Objekt KEIN et: רואה ילד." },
        { type: "form", prompt: "„mich“ (als Objekt)",
          options: [ { he: "אותי", translit: "oti", correct: true }, { he: "לי", translit: "li" } ],
          note: "Objektform: אותי (oti). לי (li) wäre „mir“ (le-Form)." },
        { type: "cloze", he: "הוא אוהב ___", translit: "hu ohev ___", de: "Er liebt dich. (eine Frau ist gemeint)",
          options: [ { he: "אותך", translit: "otach", correct: true }, { he: "אותו", translit: "oto" } ],
          note: "„dich“ (f) = אותך (otach); אותו (oto) wäre „ihn“." },
        { type: "cloze", he: "אני מכיר ___", translit: "ani makir ___", de: "Ich kenne ihn.",
          options: [ { he: "אותו", translit: "oto", correct: true }, { he: "אותה", translit: "ota" } ],
          note: "„ihn“ = אותו (oto); אותה (ota) wäre „sie“." },
        { type: "form", prompt: "„uns“ (als Objekt)",
          options: [ { he: "אותנו", translit: "otanu", correct: true }, { he: "אנחנו", translit: "anachnu" } ],
          note: "Objektform: אותנו (otanu). אנחנו (anachnu) ist „wir“ (Subjekt)." }
      ]
    },

    // ===================== Band B2 =====================
    {
      id: "mod_gram_passiv", title: "Passiv erkennen", emoji: "🔁", band: "B2", group: "grammar",
      sub: "nif'al, pu'al, huf'al - wenn etwas mit einem gemacht wird.",
      steps: [
        { type: "explain", title: "Drei passive Bauformen",
          text: "Zu den aktiven Binjanim gehören passive Gegenstücke: nif'al (Passiv/Medium zu pa'al), pu'al (Passiv zu pi'el) und huf'al (Passiv zu hif'il). Statt „jemand schreibt den Brief“ heißt es dann „der Brief wird geschrieben“.",
          examples: [ { he: "כתב ← נכתב", translit: "katav / nichtav", de: "schrieb / wurde geschrieben" }, { he: "נגמר", translit: "nigmar", de: "wurde beendet / ging zu Ende" }, { he: "מדובר", translit: "medubar", de: "wird gesprochen (pu'al)" } ] },
        { type: "explain", title: "nif'al erkennst du am נ",
          text: "nif'al beginnt in der Vergangenheit mit נ (n-): נכתב (nichtav, wurde geschrieben), נגמר (nigmar, ging zu Ende), נכנס (nichnas, trat ein). pu'al und huf'al erkennst du im Präsens am מ mit „u“-Vokal: מדובר (medubar).",
          examples: [ { he: "נכתב", translit: "nichtav", de: "wurde geschrieben (nif'al)" }, { he: "נגמר", translit: "nigmar", de: "ging zu Ende (nif'al)" }, { he: "מדובר", translit: "medubar", de: "wird gesprochen (pu'al)" } ] },
        { type: "form", prompt: "„wurde geschrieben“ (Passiv, nif'al)",
          options: [ { he: "נכתב", translit: "nichtav", correct: true }, { he: "כתב", translit: "katav" } ],
          note: "Passiv: נכתב (nichtav). כתב (katav) = „schrieb“ (aktiv)." },
        { type: "cloze", he: "המכתב ___ אתמול", translit: "ha-michtav ___ etmol", de: "Der Brief wurde gestern geschrieben.",
          options: [ { he: "נכתב", translit: "nichtav", correct: true }, { he: "כתב", translit: "katav" } ],
          note: "„wurde geschrieben“ = נכתב (nichtav)." },
        { type: "form", prompt: "„ging zu Ende / wurde beendet“ (nif'al)",
          options: [ { he: "נגמר", translit: "nigmar", correct: true }, { he: "גמר", translit: "gamar" } ],
          note: "נגמר (nigmar, nif'al) mit נ vorn. גמר (gamar) = „beendete“ (aktiv)." },
        { type: "cloze", he: "הסרט כבר ___", translit: "ha-seret kvar ___", de: "Der Film ist schon zu Ende (wurde beendet).",
          options: [ { he: "נגמר", translit: "nigmar", correct: true }, { he: "גמר", translit: "gamar" } ],
          note: "Hier passt das Passiv/Medium נגמר (nigmar)." },
        { type: "form", prompt: "„es wird gesprochen / die Rede ist von“ (pu'al)",
          options: [ { he: "מדובר", translit: "medubar", correct: true }, { he: "מדבר", translit: "medaber" } ],
          note: "מדובר (medubar, pu'al) = wird gesprochen. מדבר (medaber, pi'el) = spricht (aktiv)." }
      ]
    },
    {
      id: "mod_gram_konditional", title: "Konditional (wenn ...)", emoji: "🤔", band: "B2", group: "grammar",
      sub: "„wenn“ real (im) und irreal (ilu) - zwei Wörter, zwei Welten.",
      steps: [
        { type: "explain", title: "Realer Fall: im + Zukunft",
          text: "Für einen realen, möglichen Fall benutzt du אם (im, wenn) - typisch zusammen mit Zukunft oder Präsens: אם יהיה זמן, אבוא (im yihye zman, avo) = „Wenn Zeit ist, komme ich“. Es kann tatsächlich so kommen.",
          examples: [ { he: "אם יהיה זמן", translit: "im yihye zman", de: "wenn Zeit ist (real)" }, { he: "אם תרצה", translit: "im tirtse", de: "wenn du willst" } ] },
        { type: "explain", title: "Irrealer Fall: ilu/lu + Vergangenheit",
          text: "Für einen hypothetischen, unwahrscheinlichen oder gegenteiligen Fall nimmst du אילו (ilu) oder לו (lu) - mit Vergangenheit, oft mit היה (haya): אילו הייתי עשיר, הייתי נוסע (ilu hayiti ashir, hayiti nose'a) = „Wenn ich reich wäre, würde ich reisen“.",
          examples: [ { he: "אילו הייתי עשיר", translit: "ilu hayiti ashir", de: "wenn ich reich wäre (irreal)" }, { he: "לו ידעתי", translit: "lu yadati", de: "wenn ich es gewusst hätte" } ] },
        { type: "cloze", he: "___ יהיה זמן, אבוא", translit: "___ yihye zman, avo", de: "Wenn Zeit ist, komme ich. (realer Fall)",
          options: [ { he: "אם", translit: "im", correct: true }, { he: "אילו", translit: "ilu" } ],
          note: "Realer Fall mit Zukunft → אם (im)." },
        { type: "cloze", he: "אילו ___ עשיר, הייתי נוסע", translit: "ilu ___ ashir, hayiti nose'a", de: "Wenn ich reich wäre, würde ich reisen.",
          options: [ { he: "הייתי", translit: "hayiti", correct: true }, { he: "אהיה", translit: "ehye" } ],
          note: "Nach אילו (irreal) steht die Vergangenheit: הייתי (hayiti)." },
        { type: "form", prompt: "„wenn“ für einen realen, möglichen Fall",
          options: [ { he: "אם", translit: "im", correct: true }, { he: "אילו", translit: "ilu" } ],
          note: "Real: אם (im). Irreal: אילו (ilu)." },
        { type: "form", prompt: "„wenn“ für einen irrealen Fall (wäre/hätte)",
          options: [ { he: "אילו", translit: "ilu", correct: true }, { he: "אם", translit: "im" } ],
          note: "Irreal/hypothetisch: אילו (ilu)." },
        { type: "cloze", he: "אם ___ יפה מחר, נלך לים", translit: "im ___ yafe machar, nelech la-yam", de: "Wenn es morgen schön ist, gehen wir ans Meer.",
          options: [ { he: "יהיה", translit: "yihye", correct: true }, { he: "היה", translit: "haya" } ],
          note: "Realer Fall mit אם → Zukunft יהיה (yihye)." },
        { type: "cloze", he: "לו ___ יודע, הייתי אומר לך", translit: "lu ___ yode'a, hayiti omer lecha", de: "Wenn ich es gewusst hätte, hätte ich es dir gesagt.",
          options: [ { he: "הייתי", translit: "hayiti", correct: true }, { he: "אני", translit: "ani" } ],
          note: "Irreal mit לו: הייתי יודע (hayiti yode'a)." }
      ]
    },
    {
      id: "mod_gram_relativ", title: "Relativsätze mit „she-“", emoji: "🪢", band: "B2", group: "grammar",
      sub: "Ein einziges ש verbindet Sätze: „der, die, das, dass“.",
      steps: [
        { type: "explain", title: "ש als Alleskönner",
          text: "Die Vorsilbe ש (she-) leitet Relativsätze ein und heißt je nach Kontext „der/die/das“ oder „dass“. Sie klebt am nächsten Wort: האיש שגר פה (ha-ish she-gar po) = „der Mann, der hier wohnt“.",
          examples: [ { he: "האיש שגר פה", translit: "ha-ish she-gar po", de: "der Mann, der hier wohnt" }, { he: "המסעדה שאהבתי", translit: "ha-mis'ada she-ahavti", de: "das Restaurant, das ich mochte" } ] },
        { type: "explain", title: "„dass“ ist dasselbe Wort",
          text: "Auch für „dass“ nach Verben des Sagens/Denkens nimmst du ש: אמרתי שאני בא (amarti she-ani ba) = „Ich sagte, dass ich komme“. In gehobener Schriftsprache gibt es dafür auch אשר (asher), im Alltag reicht ש.",
          examples: [ { he: "אמרתי שאני בא", translit: "amarti she-ani ba", de: "ich sagte, dass ich komme" }, { he: "חושב שכן", translit: "choshev she-ken", de: "ich denke, dass ja / schon" } ] },
        { type: "cloze", he: "האיש ___ גר פה", translit: "ha-ish ___ gar po", de: "Der Mann, der hier wohnt.",
          options: [ { he: "ש", translit: "she-", correct: true }, { he: "מה", translit: "ma" } ],
          note: "Relativ „der“ = ש (she-). מה (ma) ist „was“." },
        { type: "cloze", he: "הספר ___ קניתי", translit: "ha-sefer ___ kaniti", de: "Das Buch, das ich gekauft habe.",
          options: [ { he: "ש", translit: "she-", correct: true }, { he: "את", translit: "et" } ],
          note: "Relativsatz mit ש (she-). את (et) markiert Objekte, verbindet aber keine Sätze." },
        { type: "cloze", he: "אמרתי ___ אני בא", translit: "amarti ___ ani ba", de: "Ich sagte, dass ich komme.",
          options: [ { he: "ש", translit: "she-", correct: true }, { he: "כי", translit: "ki" } ],
          note: "„dass“ = ש (she-). כי (ki) heißt „weil“." },
        { type: "form", prompt: "„der/die/das“ als Verbindung - die Alltagsform",
          options: [ { he: "ש", translit: "she-", correct: true }, { he: "אשר", translit: "asher" } ],
          note: "Alltag: ש (she-). אשר (asher) ist dasselbe, aber gehoben/schriftlich." },
        { type: "cloze", he: "זה הבית ___ אני אוהב", translit: "ze ha-bayit ___ ani ohev", de: "Das ist das Haus, das ich mag.",
          options: [ { he: "ש", translit: "she-", correct: true }, { he: "זה", translit: "ze" } ],
          note: "Relativsatz braucht ש (she-)." }
      ]
    },

    // ===================== Band C1 =====================
    {
      id: "mod_gram_hitpael", title: "Hitpa'el & Verbalnomen", emoji: "🪞", band: "C1", group: "grammar",
      sub: "Reflexive Verben und das „das ...en“ (shem pe'ula).",
      steps: [
        { type: "explain", title: "Hitpa'el: die Handlung kehrt zurück",
          text: "Der Binjan hitpa'el drückt oft Reflexives oder Gegenseitiges aus und trägt vorn hit-/mit-: התלבש (hitlabesh, zog sich an), הסתכל (histakel, schaute), התרגש (hitragesh, wurde aufgeregt). Im Präsens beginnt er mit מת (mit-): מתלבש (mitlabesh).",
          examples: [ { he: "מתלבש", translit: "mitlabesh", de: "zieht sich an" }, { he: "מתרגש", translit: "mitragesh", de: "ist/wird aufgeregt" }, { he: "מסתכל", translit: "mistakel", de: "schaut / betrachtet" } ] },
        { type: "explain", title: "Shem pe'ula: das Verb als Nomen",
          text: "Jeder Binjan hat ein Verbalnomen (shem pe'ula), das die Handlung benennt - im Deutschen oft „das ...en“. pa'al: כתיבה (ktiva, das Schreiben), אכילה (achila, das Essen). pi'el: דיבור (dibur, das Reden), טיול (tiyul, Ausflug). hif'il: הזמנה (hazmana, Bestellung/Einladung).",
          examples: [ { he: "כתיבה", translit: "ktiva", de: "das Schreiben" }, { he: "דיבור", translit: "dibur", de: "das Reden" }, { he: "הזמנה", translit: "hazmana", de: "Einladung / Bestellung" } ] },
        { type: "form", prompt: "„er zieht sich an“ (hitpa'el, reflexiv)",
          options: [ { he: "מתלבש", translit: "mitlabesh", correct: true }, { he: "לובש", translit: "lovesh" } ],
          note: "Reflexiv: מתלבש (mitlabesh). לובש (lovesh, pa'al) = „zieht etwas an“." },
        { type: "cloze", he: "אני ___ מהסרט", translit: "ani ___ me-ha-seret", de: "Ich bin aufgeregt wegen des Films. (ein Mann spricht)",
          options: [ { he: "מתרגש", translit: "mitragesh", correct: true }, { he: "מרגש", translit: "meragesh" } ],
          note: "Sich aufregen (reflexiv): מתרגש (mitragesh). מרגש (meragesh) = „erregend“ (aktiv, es regt an)." },
        { type: "form", prompt: "Verbalnomen zu „schreiben“ (das Schreiben)",
          options: [ { he: "כתיבה", translit: "ktiva", correct: true }, { he: "כותב", translit: "kotev" } ],
          note: "כתיבה (ktiva) ist das Nomen; כותב (kotev) ist das Verb „schreibt“." },
        { type: "form", prompt: "Verbalnomen zu „reden“ (das Reden, aus pi'el)",
          options: [ { he: "דיבור", translit: "dibur", correct: true }, { he: "מדבר", translit: "medaber" } ],
          note: "דיבור (dibur) = das Reden; מדבר (medaber) = „spricht“." },
        { type: "cloze", he: "קיבלתי ___ למסיבה", translit: "kibalti ___ la-mesiba", de: "Ich bekam eine Einladung zur Party.",
          options: [ { he: "הזמנה", translit: "hazmana", correct: true }, { he: "מזמין", translit: "mazmin" } ],
          note: "הזמנה (hazmana) = Einladung (Verbalnomen von hif'il). מזמין (mazmin) = „lädt ein“ (Verb)." },
        { type: "form", prompt: "„sie schauen / betrachten“ (hitpa'el, Mehrzahl m)",
          options: [ { he: "מסתכלים", translit: "mistaklim", correct: true }, { he: "מסתכל", translit: "mistakel" } ],
          note: "Mehrzahl: מסתכלים (mistaklim); Einzahl מסתכל (mistakel)." }
      ]
    },
    {
      id: "mod_gram_register", title: "Register: formell vs. Slang", emoji: "🎚", band: "C1", group: "grammar",
      sub: "Amtssprache oder Straße - dasselbe meinen, anders klingen.",
      steps: [
        { type: "explain", title: "Zwei Ebenen derselben Sprache",
          text: "Hebräisch hat einen deutlichen Abstand zwischen gehobener Schrift-/Amtssprache und lockerer Umgangssprache. „Ich möchte“ heißt im Alltag אני רוצה (ani rotze), formell eher אני מעוניין (ani me'unyan) oder אני מבקש (ani mevakesh). Auf Schildern liest du נא (na, „bitte“) statt eines direkten Befehls.",
          examples: [ { he: "אני רוצה", translit: "ani rotze", de: "ich will (Alltag)" }, { he: "אני מעוניין", translit: "ani me'unyan", de: "ich möchte (formell)" }, { he: "נא לא לעשן", translit: "na lo le'ashen", de: "bitte nicht rauchen (Schild)" } ] },
        { type: "explain", title: "Der Slang-Werkzeugkasten",
          text: "Umgekehrt gibt es viele Alltagswörtchen, die in einem Brief oder Antrag nichts verloren haben: סבבה (sababa, super), אחלה (achla, klasse), יאללה (yalla, los/komm), וואלה (walla, echt?). Erkennen ist wichtig - selbst benutzen nur im richtigen Rahmen.",
          examples: [ { he: "סבבה", translit: "sababa", de: "super/okay (Slang)" }, { he: "יאללה", translit: "yalla", de: "los, komm (Slang)" }, { he: "וואלה", translit: "walla", de: "echt?/wow (Slang)" } ] },
        { type: "form", prompt: "„ich möchte“ - die gehobene, formelle Variante",
          options: [ { he: "מעוניין", translit: "me'unyan", correct: true }, { he: "רוצה", translit: "rotze" } ],
          note: "Formell: מעוניין (me'unyan). רוצה (rotze) ist Alltag." },
        { type: "form", prompt: "„bitte nicht rauchen“ - so steht es formell auf dem Schild",
          options: [ { he: "נא לא לעשן", translit: "na lo le'ashen", correct: true }, { he: "אסור לעשן", translit: "asur le'ashen" } ],
          note: "נא (na) klingt höflich-formell; אסור (asur, „verboten“) ist direkter." },
        { type: "form", prompt: "Welches Wort ist Slang für „super/klasse“?",
          options: [ { he: "סבבה", translit: "sababa", correct: true }, { he: "טוב", translit: "tov" } ],
          note: "סבבה (sababa) ist salopp; טוב (tov, „gut“) ist neutral." },
        { type: "form", prompt: "„los / komm schon“ - Umgangssprache",
          options: [ { he: "יאללה", translit: "yalla", correct: true }, { he: "בבקשה", translit: "bevakasha" } ],
          note: "יאללה (yalla) ist Alltag/Slang; בבקשה (bevakasha) ist neutral „bitte“." },
        { type: "form", prompt: "„echt? / wow“ - salopper Ausruf",
          options: [ { he: "וואלה", translit: "walla", correct: true }, { he: "באמת", translit: "be'emet" } ],
          note: "וואלה (walla) ist salopp; באמת (be'emet) ist neutral „wirklich“." }
      ]
    },

    // ===================== Band C2 =====================
    {
      id: "mod_gram_gehoben", title: "Gehobene Formen", emoji: "📜", band: "C2", group: "grammar",
      sub: "Literarisches Hebräisch, das im modernen Text noch lebt.",
      steps: [
        { type: "explain", title: "Wörter für die Schriftsprache",
          text: "In gehobenen Texten (Literatur, Reden, Zeitungskommentar) tauchen Formen auf, die man kaum spricht: אשר (asher) statt ש, כאשר (ka'asher) statt כש (kshe-). Auch אין (ein) hat eine gehobene Seite: im Alltag heißt es schlicht „es gibt nicht“, in der Schriftsprache verneint es ganze Nominalsätze, z. B. אין הדבר נכון (ein ha-davar nachon, „dem ist nicht so“).",
          examples: [ { he: "אשר", translit: "asher", de: "der/welcher (gehoben)" }, { he: "כאשר", translit: "ka'asher", de: "als/wenn (gehoben)" }, { he: "בטרם", translit: "beterem", de: "bevor (literarisch)" } ] },
        { type: "explain", title: "Zeit- und Grad-Partikel mit Stil",
          text: "Gehobene Zeitwörter: טרם (terem, „noch nicht“), בטרם (beterem, „bevor“), לעולם לא (le'olam lo, „niemals“). Sie klingen bewusst formell und ersetzen im Text die Alltagsformen wie עוד לא (od lo) oder אף פעם (af pa'am).",
          examples: [ { he: "טרם", translit: "terem", de: "noch nicht (gehoben)" }, { he: "לעולם לא", translit: "le'olam lo", de: "niemals (nachdrücklich)" }, { he: "בטרם", translit: "beterem", de: "bevor" } ] },
        { type: "form", prompt: "„der/welcher“ - die literarisch-gehobene Form",
          options: [ { he: "אשר", translit: "asher", correct: true }, { he: "ש", translit: "she-" } ],
          note: "אשר (asher) = gehoben; ש (she-) = Alltag, gleiche Bedeutung." },
        { type: "form", prompt: "„als / wenn“ - gehoben (schriftlich)",
          options: [ { he: "כאשר", translit: "ka'asher", correct: true }, { he: "כש", translit: "kshe-" } ],
          note: "כאשר (ka'asher) = schriftlich; כש (kshe-) = gesprochen." },
        { type: "form", prompt: "„bevor“ - die literarische Variante",
          options: [ { he: "בטרם", translit: "beterem", correct: true }, { he: "לפני ש", translit: "lifney she-" } ],
          note: "בטרם (beterem) = gehoben; לפני ש (lifney she-) = Alltag." },
        { type: "cloze", he: "הוא ___ הגיע", translit: "hu ___ higia", de: "Er ist noch nicht angekommen. (gehoben)",
          options: [ { he: "טרם", translit: "terem", correct: true }, { he: "עוד לא", translit: "od lo" } ],
          note: "טרם (terem) ist das literarische „noch nicht“; עוד לא (od lo) wäre Alltag." },
        { type: "form", prompt: "„niemals“ - nachdrücklich/gehoben",
          options: [ { he: "לעולם לא", translit: "le'olam lo", correct: true }, { he: "אף פעם", translit: "af pa'am" } ],
          note: "לעולם לא (le'olam lo) ist nachdrücklich; אף פעם (af pa'am) ist Umgangssprache." },
        { type: "cloze", he: "___ ברירה אחרת", translit: "___ brera acheret", de: "Es gibt keine andere Wahl.",
          options: [ { he: "אין", translit: "ein", correct: true }, { he: "לא", translit: "lo" } ],
          note: "„es gibt kein“ = אין (ein); לא (lo) verneint Verben." }
      ]
    },
    {
      id: "mod_gram_syntax", title: "Idiomatische Syntax", emoji: "🔀", band: "C2", group: "grammar",
      sub: "Voranstellung, Betonung und das fehlende „haben“.",
      steps: [
        { type: "explain", title: "Voranstellung zur Betonung (Fronting)",
          text: "Die Grundstellung ist meist Subjekt-Verb-Objekt, aber du kannst ein betontes Element nach vorn holen: אותו אני מכיר טוב (oto ani makir tov) = „IHN kenne ich gut“. Das vorangestellte Objekt behält seine Objektform (oto, nicht hu).",
          examples: [ { he: "אותו אני מכיר", translit: "oto ani makir", de: "IHN kenne ich (betont)" }, { he: "את זה כבר ראיתי", translit: "et ze kvar raiti", de: "DAS habe ich schon gesehen" } ] },
        { type: "explain", title: "Kein Verb für „haben“",
          text: "Besitz und Existenz laufen ohne „haben/sein“: יש לי (yesh li) = „ich habe“ (wörtlich „es gibt mir“). Und betonende Partikel wie דווקא (davka, „ausgerechnet/gerade“) verschieben die Aussage fein, ohne die Wortstellung umzubauen.",
          examples: [ { he: "יש לי רעיון", translit: "yesh li ra'ayon", de: "ich habe eine Idee" }, { he: "דווקא כן", translit: "davka ken", de: "gerade doch / sehr wohl" } ] },
        { type: "cloze", he: "___ אני מכיר טוב", translit: "___ ani makir tov", de: "IHN kenne ich gut. (Betonung durch Voranstellung)",
          options: [ { he: "אותו", translit: "oto", correct: true }, { he: "הוא", translit: "hu" } ],
          note: "Das vorangestellte Objekt bleibt Objektform: אותו (oto), nicht הוא (hu)." },
        { type: "cloze", he: "את זה כבר ___", translit: "et ze kvar ___", de: "Das habe ich schon gesehen.",
          options: [ { he: "ראיתי", translit: "raiti", correct: true }, { he: "רואה", translit: "ro'e" } ],
          note: "„schon gesehen“ ist Vergangenheit: ראיתי (raiti)." },
        { type: "form", prompt: "„gerade / ausgerechnet“ - betonende Partikel",
          options: [ { he: "דווקא", translit: "davka", correct: true }, { he: "אולי", translit: "ulai" } ],
          note: "דווקא (davka) betont/kontrastiert; אולי (ulai) heißt „vielleicht“." },
        { type: "cloze", he: "יש ___ רעיון טוב", translit: "yesh ___ ra'ayon tov", de: "Ich habe eine gute Idee. (Besitz mit yesh)",
          options: [ { he: "לי", translit: "li", correct: true }, { he: "אני", translit: "ani" } ],
          note: "Besitz = yesh + le-Form: יש לי (yesh li)." },
        { type: "form", prompt: "„ich habe“ - so baut Hebräisch es (es gibt kein Verb „haben“)",
          options: [ { he: "יש לי", translit: "yesh li", correct: true }, { he: "אני יש", translit: "ani yesh" } ],
          note: "Feste Wendung: יש לי (yesh li), nicht *ani yesh." },
        { type: "cloze", he: "___ הלכתי, לא לים", translit: "___ halachti, lo la-yam", de: "In die STADT ging ich, nicht ans Meer. (vorangestellte Ortsangabe)",
          options: [ { he: "לעיר", translit: "la-ir", correct: true }, { he: "העיר", translit: "ha-ir" } ],
          note: "Vorangestellte Richtungsangabe braucht die Präposition: לעיר (la-ir)." }
      ]
    }

  ]
};
